"""Generate CAA's five-position exact bipartite assignment dynamic program.

Each candidate is processed once, masks in descending order. Consequently a
candidate cannot occupy two seats. States retain the best additive vector:
mandatory incumbents, powerful vassals, (10 * total skill + unchanged seats).
Final selection adds filled-seat cardinality between mandatory and powerful.
The mandatory component is a constraint used only with replacement disabled.
No shortlist or skill cap is used, so unusual/modded skill values remain exact.
"""
from pathlib import Path

ROOT = Path(__file__).absolute().parents[1]
MOD = ROOT / "mod/council_assignment_automation"
ROLES = [("chancellor", "diplomacy"), ("steward", "stewardship"),
         ("marshal", "martial"), ("spymaster", "intrigue"),
         ("court_chaplain", "learning")]


def write(relative, content):
    path = MOD / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8-sig")


def indent(text, n=1):
    return "\n".join("\t" * n + line if line else "" for line in text.splitlines())


def setvar(name, value):
    return f"set_variable = {{ name = {name} value = {value} }}"


def block(key, text):
    return f"{key} = {{\n{indent(text)}\n}}"


def lex_gt(left, right):
    """Generate comparison of an ordered sequence of script values."""
    cases = []
    for i in range(len(left)):
        lines = [f"{left[j]} = {right[j]}" for j in range(i)]
        lines.append(f"{left[i]} > {right[i]}")
        cases.append(block("AND", "\n".join(lines)))
    return block("OR", "\n".join(cases))


triggers = """
# All settings are per-player-character variables; no AI council is automated.
caa_supported_ruler_trigger = {
    is_alive = yes
    is_ai = no
    is_landed = yes
    has_council = yes
    NOT = { government_has_flag = government_is_nomadic }
    NOT = { government_has_flag = government_is_landless_adventurer }
    tgp_has_access_to_ministry_trigger = no
}

# Current actor is saved by caa_run_assignment_effect.
caa_candidate_pool_trigger = {
    is_alive = yes
    NOT = { this = scope:caa_owner }
    OR = {
        is_courtier_of = scope:caa_owner
        is_vassal_of = scope:caa_owner
    }
    trigger_if = {
        limit = { is_councillor_of = scope:caa_owner }
        OR = {
"""
for i, (role, _) in enumerate(ROLES):
    triggers += f"""            AND = {{
                has_council_position = councillor_{role}
                scope:caa_owner = {{ has_variable = caa_open_{i} }}
            }}
"""
triggers += """        }
    }
}
"""
for i, (role, _) in enumerate(ROLES):
    triggers += f"""
caa_candidate_for_{role}_trigger = {{
    scope:caa_owner = {{ has_variable = caa_open_{i} }}
    OR = {{
        valid_for_council_position = councillor_{role}
        # Off preserves an existing incumbent even if new-appointment eligibility
        # changed since appointment. Cross-role moves still require native validity.
        AND = {{
            scope:caa_owner = {{ NOT = {{ has_variable = caa_observer }} has_variable = caa_old_{i} }}
            is_alive = yes
            scope:caa_owner.var:caa_old_{i} ?= this
        }}
    }}
}}
"""
write("common/scripted_triggers/caa_triggers.txt", triggers)

values = "# Scoring leaves one skill point larger than all five stability bonuses.\n"
for i, (role, skill) in enumerate(ROLES):
    values += f"""
caa_{role}_score_value = {{
    value = {skill}
    multiply = 10
    if = {{
        limit = {{ scope:caa_owner.var:caa_old_{i} ?= this }}
        add = 1
    }}
}}
"""
write("common/script_values/caa_values.txt", values)

effects = """
# Generated by tools/generate_council_assignment.py. Edit the generator.
# The 32-state DP is exact across all eligible courtiers and direct vassals.
# It never assigns a character twice and never dismisses a protected incumbent.

caa_schedule_effect = {
    if = {
        limit = {
            is_alive = yes
            is_ai = no
            has_variable = caa_enabled
            NOT = { has_variable = caa_tick_pending }
        }
        set_variable = { name = caa_tick_pending value = yes }
        trigger_event = { id = caa.0001 days = 30 }
    }
}

caa_toggle_enabled_effect = {
    if = {
        limit = { has_variable = caa_enabled }
        remove_variable = caa_enabled
        # Keep pending until its event drains: rapid off/on cannot create duplicates.
    }
    else_if = {
        limit = { caa_supported_ruler_trigger = yes }
        set_variable = { name = caa_enabled value = yes }
        caa_run_assignment_effect = yes
        caa_schedule_effect = yes
    }
}

caa_toggle_powerful_effect = {
    if = {
        limit = { has_variable = caa_prioritize_powerful }
        remove_variable = caa_prioritize_powerful
    }
    else = { set_variable = { name = caa_prioritize_powerful value = yes } }
    caa_run_assignment_effect = yes
}

caa_toggle_observer_effect = {
    if = {
        limit = { has_variable = caa_observer }
        remove_variable = caa_observer
    }
    else = { set_variable = { name = caa_observer value = yes } }
    caa_run_assignment_effect = yes
}
"""

# Mark seats that are available for this run and record all current incumbents.
prepare = []
for i, (role, _) in enumerate(ROLES):
    cp = f"cp:councillor_{role}"
    prepare.append(f"{cp} ?= {{ scope:caa_owner = {{ {setvar(f'caa_old_{i}', 'prev')} }} }}")
    chapel = "\nrite = { rite_has_parameter = clerical_appointment_ruler }" if i == 4 else ""
    prepare.append(f"""if = {{
    limit = {{
        exists = council_task:councillor_{role}{chapel}
        OR = {{
            NOT = {{ exists = {cp} }}
            AND = {{
                {cp} = {{ can_be_fired_from_council_trigger = {{ COURT_OWNER = scope:caa_owner }} }}
                OR = {{
                    has_variable = caa_observer
                    AND = {{
                        has_variable = caa_prioritize_powerful
                        {cp} = {{ is_powerful_vassal_of = scope:caa_owner }}
                    }}
                }}
            }}
        }}
    }}
    {setvar(f'caa_open_{i}', 'yes')}
}}""")
effects += "\n" + block("caa_prepare_seats_effect", "\n".join(prepare)) + "\n"

# Candidate scoring is cached once per role; persistent scratch vars are removed
# in the same synchronous effect before CK3 can advance, save, or accept input.
score = ["save_scope_as = caa_candidate", "scope:caa_owner = {"]
score += [indent(setvar("caa_candidate_keep", 0)), indent(setvar("caa_candidate_power", 0))]
score += ["""    if = {
        limit = {
            NOT = { has_variable = caa_observer }
            scope:caa_candidate = { is_councillor_of = scope:caa_owner }
        }
        set_variable = { name = caa_candidate_keep value = 1 }
    }
    if = {
        limit = {
            has_variable = caa_prioritize_powerful
            scope:caa_candidate = { is_powerful_vassal_of = scope:caa_owner }
        }
        set_variable = { name = caa_candidate_power value = 1 }
    }"""]
for i, (role, _) in enumerate(ROLES):
    score += [f"""    remove_variable = caa_candidate_score_{i}
    if = {{
        limit = {{ scope:caa_candidate = {{ caa_candidate_for_{role}_trigger = yes }} }}
        {setvar(f'caa_candidate_score_{i}', f'scope:caa_candidate.caa_{role}_score_value')}
    }}"""]
score += ["    caa_dp_candidate_effect = yes", "}"]
effects += "\n" + block("caa_score_candidate_effect", "\n".join(score)) + "\n"

dp = []
for mask in range(30, -1, -1):
    for i in range(5):
        if mask & (1 << i):
            continue
        dst = mask | (1 << i)
        sums = []
        for kind, extra in [("keep", "keep"), ("power", "power"), ("score", f"score_{i}")]:
            sums.append(setvar(f"caa_try_{kind}", f"{{ value = var:caa_dp_{mask}_{kind} add = var:caa_candidate_{extra} }}"))
        cmp = lex_gt([f"var:caa_try_{k}" for k in ("keep", "power", "score")],
                     [f"var:caa_dp_{dst}_{k}" for k in ("keep", "power", "score")])
        copy = [setvar(f"caa_dp_{dst}_{k}", f"var:caa_try_{k}") for k in ("keep", "power", "score")]
        for j in range(5):
            if dst & (1 << j):
                copy.append(setvar(f"caa_dp_{dst}_seat_{j}", "scope:caa_candidate" if i == j else f"var:caa_dp_{mask}_seat_{j}"))
        dp.append(f"""# Candidate to seat {i}: mask {mask:05b} -> {dst:05b}.
if = {{
    limit = {{ has_variable = caa_dp_{mask}_score has_variable = caa_candidate_score_{i} }}
{indent(chr(10).join(sums))}
    if = {{
        limit = {{
            OR = {{
                NOT = {{ has_variable = caa_dp_{dst}_score }}
{indent(cmp, 4)}
            }}
        }}
{indent(chr(10).join(copy), 2)}
    }}
}}""")
effects += "\n" + block("caa_dp_candidate_effect", "\n".join(dp)) + "\n"

select = [setvar("caa_best_keep", -1), setvar("caa_best_fill", -1),
          setvar("caa_best_power", -1), setvar("caa_best_score", -1)]
for mask in range(32):
    count = mask.bit_count()
    cmp = lex_gt([f"var:caa_dp_{mask}_keep", f"{count}", f"var:caa_dp_{mask}_power", f"var:caa_dp_{mask}_score"],
                 ["var:caa_best_keep", "var:caa_best_fill", "var:caa_best_power", "var:caa_best_score"])
    # CK3 comparisons require the left hand to be a named numeric expression.
    cmp = cmp.replace(f"{count} = var:caa_best_fill", f"var:caa_best_fill = {count}")
    cmp = cmp.replace(f"{count} > var:caa_best_fill", f"var:caa_best_fill < {count}")
    copy = [setvar("caa_best_keep", f"var:caa_dp_{mask}_keep"), setvar("caa_best_fill", count),
            setvar("caa_best_power", f"var:caa_dp_{mask}_power"), setvar("caa_best_score", f"var:caa_dp_{mask}_score")]
    for j in range(5):
        copy += [setvar(f"caa_best_{j}", f"var:caa_dp_{mask}_seat_{j}") if mask & (1 << j)
                 else f"remove_variable = caa_best_{j}"]
    select += [f"""if = {{
    limit = {{
        has_variable = caa_dp_{mask}_score
{indent(cmp, 2)}
    }}
{indent(chr(10).join(copy))}
}}"""]
effects += "\n" + block("caa_select_best_effect", "\n".join(select)) + "\n"

apply = []
for i, (role, _) in enumerate(ROLES):
    in_best = "\n".join(f"scope:caa_owner.var:caa_best_{j} ?= this" for j in range(5))
    apply += [f"""if = {{
    limit = {{
        has_variable = caa_open_{i}
        has_variable = caa_old_{i}
    }}
    if = {{
        # Put the optional (possibly unfilled) destination on the LEFT.
        # CK3 does not suppress an unset right-hand scope inside an OR.
        limit = {{ NOT = {{ var:caa_best_{i} ?= var:caa_old_{i} }} }}
    if = {{
        limit = {{ var:caa_old_{i} = {{ OR = {{
{indent(in_best, 3)}
        }} }} }}
        # Retained councillors are moving roles, not being dismissed.
        fire_councillor_skip_effects = var:caa_old_{i}
    }}
    else = {{ fire_councillor = var:caa_old_{i} }}
    }}
}}"""]
for i, (role, _) in enumerate(ROLES):
    apply += [f"""if = {{
    limit = {{ has_variable = caa_best_{i} }}
    if = {{
    limit = {{
        NOT = {{ cp:councillor_{role} ?= var:caa_best_{i} }}
        var:caa_best_{i} = {{ valid_for_council_position = councillor_{role} }}
    }}
    assign_councillor_type = {{ type = councillor_{role} target = var:caa_best_{i} }}
    }}
}}"""]
effects += "\n" + block("caa_apply_best_effect", "\n".join(apply)) + "\n"

scratch = [f"caa_{kind}_{i}" for kind in ("open", "old", "best", "candidate_score") for i in range(5)]
scratch += [f"caa_{kind}_{dim}" for kind in ("best", "try") for dim in ("keep", "power", "score")]
scratch += ["caa_candidate_keep", "caa_candidate_power"]
scratch += ["caa_best_fill"]
for mask in range(32):
    scratch += [f"caa_dp_{mask}_{k}" for k in ("keep", "power", "score")]
    scratch += [f"caa_dp_{mask}_seat_{j}" for j in range(5) if mask & (1 << j)]
effects += "\n" + block("caa_clear_scratch_effect", "\n".join(f"remove_variable = {v}" for v in scratch)) + "\n"
effects += """
caa_run_assignment_effect = {
    if = {
        limit = {
            has_variable = caa_enabled
            caa_supported_ruler_trigger = yes
        }
        save_scope_as = caa_owner
        caa_clear_scratch_effect = yes
        caa_prepare_seats_effect = yes
        set_variable = { name = caa_dp_0_keep value = 0 }
        set_variable = { name = caa_dp_0_power value = 0 }
        set_variable = { name = caa_dp_0_score value = 0 }
        every_courtier = {
            limit = { caa_candidate_pool_trigger = yes }
            add_to_list = caa_candidates
        }
        every_vassal = {
            limit = {
                caa_candidate_pool_trigger = yes
                NOT = { is_in_list = caa_candidates }
            }
            add_to_list = caa_candidates
        }
        every_in_list = {
            list = caa_candidates
            caa_score_candidate_effect = yes
        }
        caa_select_best_effect = yes
        caa_apply_best_effect = yes
        caa_clear_scratch_effect = yes
        every_in_list = { list = caa_candidates remove_from_list = caa_candidates }
    }
}

caa_inherit_settings_effect = {
    if = {
        limit = { exists = scope:previous_player_character }
        if = {
            limit = { scope:previous_player_character = { has_variable = caa_enabled } }
            set_variable = { name = caa_enabled value = yes }
        }
        else = { remove_variable = caa_enabled }
        if = {
            limit = { scope:previous_player_character = { has_variable = caa_prioritize_powerful } }
            set_variable = { name = caa_prioritize_powerful value = yes }
        }
        else = { remove_variable = caa_prioritize_powerful }
        if = {
            limit = { scope:previous_player_character = { has_variable = caa_observer } }
            set_variable = { name = caa_observer value = yes }
        }
        else = { remove_variable = caa_observer }
    }
    caa_run_assignment_effect = yes
    caa_schedule_effect = yes
}
"""
write("common/scripted_effects/caa_effects.txt", effects)

write("events/caa_events.txt", """
namespace = caa

# Scheduled events and character variables are serialized by CK3 saves.
# Do not gate the event trigger: even an Off event must clear its pending marker.
caa.0001 = {
    type = character_event
    hidden = yes
    immediate = {
        remove_variable = caa_tick_pending
        caa_run_assignment_effect = yes
        caa_schedule_effect = yes
    }
}
""")

write("common/on_action/caa_on_actions.txt", """
on_player_character_change = { on_actions = { caa_on_player_character_change } }
caa_on_player_character_change = { effect = { caa_inherit_settings_effect = yes } }

# Recovery for a loaded campaign whose enabled character has no queued pulse.
on_game_start_after_lobby = { on_actions = { caa_on_start } }
caa_on_start = {
    effect = { every_player = { caa_schedule_effect = yes } }
}
""")

if __name__ == "__main__":
    print(f"Generated CAA exact DP for {len(ROLES)} positions at {MOD}")
